version: 1.2

workflows:
  - name: ampseq_experimental
    subclass: WDL
    primaryDescriptorPath: /WDL/wdl_ampseq.wdl
  - name: mhap_experimental
    subclass: WDL
    primaryDescriptorPath: /WDL/wdl_report_layouting.wdl
